services:
  - type: web
    name: nay-thar-portfolio
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && echo "=== STATIC FILES ===" && ls -lah static
    startCommand: gunicorn app:app
    healthCheckPath: /health
    autoDeploy: true